{% if include_docker %}
FROM python:3.12-slim

WORKDIR /app

COPY pdm.lock .

{% if database == 'postgres' %}
RUN apt-get update && apt-get install -y --no-install-recommends libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*
{% endif %}

RUN pip install --no-cache-dir --break-system-packages pdm && pdm sync

COPY . .

ENV PYTHONPATH=/app/src

EXPOSE {{ port }}

CMD ["python", "-m", "uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "{{ port }}"]
{% endif %}
